### ISSUE TITLE
Rebuild trellis-app form builder in vue

### ISSUE THREAD

**Issue by disperse** [human-nature-lab/trellis-app#176]
This is a bigger follow-up project to embedding the current form builder in the trellis-survey-view app.

**Comment by wyattis** [comment]
Checklist
- [x] Lock/Unlock form
- [x] Form wide locale
- [ ] Sections
  - [ ] Add
  - [ ] Remove
  - [ ] Follow up questions
  - [ ] Reordering
- [ ] Pages
  - [ ] Add
  - [ ] Remove
  - [ ] Skips
    - [ ] Add
    - [ ] Remove
    - [ ] Update
  - [ ] Reordering
- [ ] Questions
  - [ ] Add
  - [ ] Remove
  - [ ] Update
  - [ ] Reordering
  - [ ] Choices
    - [x] Add
    - [x] Remove
    - [x] Update
    - [ ] Reordering
   - [x] Parameters
     - [x] Add
     - [x] Remove
     - [x] Update
   - [x] Assign condition tags
     - [x] Add
     - [x] Remove
     - [x] Update

**Comment by wyattis** [comment]
Prerelease Chores

- [ ] Add all missing translations
  - [ ] English
  - [ ] Spanish
- [ ] Ensure the old form builder works
- [ ] Create initial versions of the new forms
