### ISSUE TITLE
CORS error on create question, form builder 

### ISSUE THREAD

**Issue by kerianVaraine** [human-nature-lab/trellis-app#323]
PUT request between site and api not processing.

I'm running Nginx server on AWS ec2 server, using the latest trellis-app 3.1.5.
Any other PUT request has no issue through my testing.

I've attached a screenshot the network pane from firefox's developer tools of a working PUT request(from creating a form), and the non functioning request(trying to create the question).

I will be doing a complete wipe and reinstall from scratch on the 16th of March, and will update if that helps.

//kerian

**PUT request not working: on question create:**

![PUT_request__not_working](https://user-images.githubusercontent.com/33189653/76692132-09578380-66b7-11ea-8e61-d71d25547a37.png)
**Console log of CORS failure associated with question create:**

![console_log-question-create-fail](https://user-images.githubusercontent.com/33189653/76692135-0b214700-66b7-11ea-9e44-f66ca34675f1.png)

**PUT request working: on form create:**
![PUT_request_working](https://user-images.githubusercontent.com/33189653/76692134-0a88b080-66b7-11ea-8358-a8f2fc9cdefa.png)

**Comment by wyattis** [comment]
Could you also post the contents of the params and response tabs?

**Comment by kerianVaraine** [comment]
output from final create question in form builder:

Nothing under Response

params:
request payload 
`{"question_type_id":"948ffae0-bfb3-4cf1-a3e9-b4845181cb61","translated_text":"q1","var_name":"q1","locale_id":"48984fbe-84d4-11e5-ba05-0800279114ca","study_id":"6db9a975-80c7-4535-bef4-6bd0cb0ce01c"}`

JSON:
![image](https://user-images.githubusercontent.com/33189653/76710028-afaf9180-6768-11ea-8110-2f80a0d1e30f.png)
