### ISSUE TITLE
Dev / Prod database, publishing forms, and versioning

### ISSUE THREAD

**Issue by disperse** [human-nature-lab/trellis-app#327]
Allows for connecting data to immutable forms, publishing forms from dev to prod makes a copy and editing forms on prod will no longer be possible.

**Comment by wyattis** [comment]
If DB switching (#357) seems unreasonable to implement, then isolating studies (#358) can help achieve the goal of having separate prod and test environments without requiring duplication and synchronization of multiple databases. One study can be used exclusively for testing and another for collecting production data.

Study isolation only solves part of the current issue with developing and testing forms. To fully deal with existing form issues we need to implement form versioning. This approach should also include a feature to make it trivial to copy forms across studies.
