### ISSUE TITLE
Bypass login requirements when downloading from proxy server

### ISSUE THREAD

**Issue by disperse** [human-nature-lab/trellis-app#330]
Is it possible to relax the login requirements when downloading from the proxy server to make it easier for the sync admin.

**Comment by wyattis** [comment]
I like this idea.

Currently the login credentials aren't saved at all on the tablet so they have to be entered repeatedly for every upload/download. Perhaps a caching mechanism of a few hours could be used to minimize this. Obviously, we don't want to store credentials on the device, but temporarily storing the authentication on the proxy server (maybe for a few hours) would be a reasonable solution if it's possible. This would allow a single login to authenticate all the uploads and downloads without allowing malicious data to be uploaded by tablets that are have been lost and minimizes the number of times the users have to login (ideally no more than twice a day).

**Comment by wyattis** [comment]
This feature has been implemented on the proxy side. The sync logic in the app needs to allow a user to start a sync without using the login screen and only be presented with the login if a 401 is returned.
